#!/bin/sh

JRUBY=`which jruby`
while getopts j: opt
do
    case "$opt" in
        j)  JRUBY="$OPTARG";;
        \?) echo >&2 \
            "Usage: $0 [-j jruby executable path]"
            exit 1;;
    esac
done

$JRUBY -S rake gems:install
$JRUBY -S rake db:setup
$JRUBY -S rake spec:rcov
