#!/bin/sh

JRUBY=`which jruby 2>/dev/null`
while getopts j: opt
do
    case "$opt" in
        j)  JRUBY="$OPTARG";;
        \?) echo >&2 \
            "Usage: $0 [-j jruby executable path]"
            exit 1;;
    esac
done

# For some reason TeamCity complains about not being able to find sqlite3
# unless I run db:setup in the same command as another rake task
$JRUBY -S rake gems:install db:setup
# If you try to run 'spec:rcov' in the same rake command as other tasks, you
# get the error "Don't know how to build task 'spec:rcov'"
$JRUBY -S rake spec:rcov
