#!/usr/bin/env ruby

require 'rubygems'
require 'lib/steamcannon/client'

api_url = 'http://localhost:8080/api'
api_name = 'lball@redhat.com'
api_pass = 'redacted'

puts "What's your API endpoint URL? (e.g. http://localhost:8080/api)"
api_url  = gets.chomp

puts "What's your steamcannon username?"
api_name = gets.chomp

puts "What's your steamcannon password?"
api_pass = gets.chomp

client = SteamCannon::API::Client.new(api_url, api_name, api_pass)

puts "Environments"
client.environments.each do |environment|
  puts "Name: #{environment.name}"
  puts "\tOwner: #{environment.owner}"
  puts "\tCurrent state: #{environment.current_state}"
  puts "\tHREF: #{environment.href}"
  puts "\tDeltacloud endpoint: #{environment.deltacloud_url}"
  puts "\tDeployments"
  environment.deployments.each do |deployment|
    puts "\t\tName: #{deployment.name}"
    puts "\t\tHREF: #{deployment.href}"
    puts "\t\tStatus: #{deployment.current_state}"
    puts
  end
  if (environment.can_stop?)
    puts "Stop this environment? Type 'yes' to stop, otherwise we won't"
    if (gets.chomp == "yes")
      puts "Stopping #{environment.name}"
      environment.stop
    else
      puts "Moving on"
    end
  end
  if (environment.can_launch?)
    puts "Launch this environment? Type 'yes' to launch, otherwise we won't"
    if (gets.chomp == "yes")
      puts "Launching #{environment.name}"
      environment.launch
    else
      puts "Moving on"
    end
  end
end

puts "\nArtifacts"
client.artifacts.each do |artifact|
  puts "Name: #{artifact.name}"
  puts "\tVersions:"
  artifact.versions.each do |version|
    puts "\tVersion #{version.id} at #{version.href}"
    unless version.deployments.nil?
      version.deployments.each do |deployment|
        puts "\t\tDeployment: #{deployment.href}"
      end
    end
  end
  puts
end

puts "\nPlatforms"
client.platforms.each do |platform|
  puts "Name: #{platform.name} ID: #{platform.id}"
  puts "URL: #{platform.href}"
  puts
end
